### ISSUE TITLE
Create 0.1.0 tag

### ISSUE THREAD

**Issue by ghost** [intuit/xhr-xdr-adapter#5]
I see your bower.json has a version of 0.1.0, but there is no 0.1.0 tag in the repository. Having git tags would help users pull in a particular version via bower. Right now the only option is to pull in the master tag, which is dangerous in case there are ever any non-backwards-compatible changes.

Thanks!

**Comment by jansensan** [comment]
+1

**Comment by lawrence858** [comment]
Done. Sorry about the long delay (not a bower user, so needed some hands-on help from one)

**Comment by dynisor** [comment]
Thanks Larry :+1: Glad we got it worked out.
