### ISSUE TITLE
Not working with Angular 2

### ISSUE THREAD

**Issue by lcrodriguez** [intuit/xhr-xdr-adapter#7]
I'm trying this on Angular 2 project. I could prepare a demo project.
Seems to be related with **Zone.js** which is adding some event listeners and for XDomainRequest may not be working fine.

```
              data.target.addEventListener('readystatechange', function () {
                if (data.target.readyState === XMLHttpRequest.DONE) {
                    if (!data.aborted) {
                        task.invoke();
                    }
                }
            });
```

**Comment by lcrodriguez** [comment]
This is the error for reference:

LOG: EXCEPTION: TypeError: Object doesn't support property or method 'addEventListener' 
LOG: EXCEPTION: TypeError: Object doesn't support property or method 'addEventListener' 
LOG: EXCEPTION: Error: Uncaught (in promise): TypeError: Object doesn't support property or method 'addEventListener' 
Unhandled Promise rejection:Object doesn't support property or method 'addEventListener'; Zone:angular; Task:Promise.then; Value:TypeError: Object doesn't support property or method 'addEventListener' 
Error: Uncaught (in promise): TypeError: Object doesn't support property or method 'addEventListener'

**Comment by lcrodriguez** [comment]
I think the offending code that uses it and crash is these line in @angular/http:

```
            _xhr.addEventListener('load', onLoad);
            _xhr.addEventListener('error', onError);
            _xhr.send(_this.request.text());
```

**Comment by briananderson1222** [comment]
Would love to hear if you get this working @lcrodriguez

**Comment by lcrodriguez** [comment]
@briananderson1222 I did. I had to tweak the adapter a bit. I will create a PR soon.

**Comment by lcrodriguez** [comment]
I've created a PR for this issue:

https://github.com/intuit/xhr-xdr-adapter/pull/8

**Comment by lawrence858** [comment]
@briananderson1222 : could you confirm whether the PR from @lcrodriguez works for you? I don't use Angular 2 and haven't had the issue that it's trying to fix. It would be super helpful if you could test it.

**Comment by ryanpetris** [comment]
@yanni858 The pull request that @lcrodriguez made worked for a project that I'm working on in Angular 4.

**Comment by lawrence858** [comment]
@lcrodriguez - thanks for your PR, @ryanpetris thanks for the confirmation. merged.
